#Steps Specific Configuration
general:
   changeManagement:
           endpoint: 'https://hclsdsm72a.hcldigilabs.com:8002/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
           clientOpts: ''
           type: 'SOLMAN'
steps:
  mtaBuild:
    buildTarget: 'NEO'
  neoDeploy:
    neoCredentialsId: 'NEO_DEPLOY'
    account: 'r15qd7iy5l'
  transportRequestUploadFile:
    applicationId: 'HCP'
