#Steps Specific Configuration
general:
   changeManagement:
           endpoint: 'http://52.184.190.82:8000/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
           clientOpts: ''
           type: 'SOLMAN'

steps:
  mtaBuild:
    buildTarget: 'NEO'
  neoDeploy:
   neo: 
    neoCredentialsId: 'NEO_DEPLOY'
    host: 'hanatrial.ondemand.com'
    account: 's0017024127trial'
    transportRequestUploadFile:
      applicationId: 'HCP'
 steps:  
     gctsCreateRepository:
    host: 'https://hcluks4hana.hcldigilabs.com:8002'
    client: '000'
    abapCredentialsId: 'ABAPUserPasswordCredentialsId'
    repository: 'myrepo'
    remoteRepositoryURL: 'https://github.com/user/myrepo'
    role: 'SOURCE'
    vSID: 'ABC'
