#Steps Specific Configuration
general:
   changeManagement:
           endpoint: 'https://hclsdsm72a.hcldigilabs.com:8002/sap/opu/odata/sap/AI_CRM_GW_CM_CI_SRV'
           clientOpts: ''
           credentialsId: 'CM'
           type: 'SOLMAN'
           solman:
            docker:
                image: ppiper/cm-client:1.0.0.0

steps:
  mtaBuild:
    buildTarget: 'NEO'
    mtaJarLocation: '/opt/sap/mta/lib/mta.jar'
    dockerImage: 'ppiper/mta-archive-builder'
  neoDeploy:
   neo: 
    neoCredentialsId: 'NEO_DEPLOY'
    host: 'hanatrial.ondemand.com'
    account: 's0016710694trial'
    transportRequestUploadFile:
      applicationId: 'HCP'
